name: Deploy Frontend to Server

on:
  push:
    branches:
      - main # Укажите ветку для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << 'EOF'
            cd /path/to/deployment  # Путь к проекту на сервере
            docker-compose -f docker-compose.dev.yaml pull frontend
            docker-compose -f docker-compose.dev.yaml up -d --build frontend
          EOF
