name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ sercrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: |
          docker build -t 20030715/frontend:latest .

      - name: Push Docker image
        run: |
          docker push 20030715/frontend:latest

      - name: SSH into server and deploy
        uses: appleboy/scp-action@v0.1.0
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} 20030715@195.49.215.169
 "cd ~/phase && docker-compose -f docker-compose.dev.yaml up -d --build frontend"
